FORMAT: 1A
HOST: https://polls.apiblueprint.org/

# Temis AI

Temis AI engine helps with the automated digitization of cross-border manuals and supports you with counsel management.

## Import DOCX [/temis]

### Extract tables from DOCX [POST]

+ Parameters

    + format (string, optional)
    
        The merged table return JSON format

        + Members
            + `split`
            + `record`
            + `index`
            + `columns`
            + `values`
            + `table`

+ Response 200 (text/html; charset=utf-8)
    + Headers

            content-length: 7
            access-control-allow-origin: *
    
    + Body

            {
                "schema": {
                    "fields": [
                    {
                        "name": "index",
                        "type": "integer"
                    },
                    {
                        "name": "CONNECTION TYPE",
                        "type": "string"
                    },
                    {
                        "name": "GROUP ",
                        "type": "string"
                    },
                    ...
                }
            }